use_frameworks!

platform :ios, '10.0'

target 'Swifty_Example' do
  pod 'RyukieSwifty', :path => '../'

  target 'Swifty_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
